language: node_js
node_js:
- 8.9.1
before_script:
- cd ..
script:
- npm install
after_script:
- git clone https://github.com/inkline/inkline inkline
- cd inkline.io
- npm link ../inkline
- npm run build

